/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "안녕하세요? 시원한 바람이 불어와 너무 기분이 좋아요 유후~";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
